version: 2.1

orbs:
 docker: circleci/docker@2.4.0

jobs:
 build:
   docker:
     - image: cimg/python:3.11

   steps:
     - checkout

     - run:
         name: install poetry
         command: pip install poetry==1.6.1

     - run:
         name: install deps
         command: poetry install

     - run:
         name: bootstrap
         command: make bootstrap

     - persist_to_workspace:
         paths:
           - ".venv"
           - "testproject"
         root: .

workflows:
 version: 2
 ci:
   jobs:
     - build

     - docker/publish:
         attach-at: .
         context: docker
         deploy: false
         docker-context: testproject/django
         extra_build_args: "--build-arg POETRY_VERSION=1.6.1 --build-arg PYTHON_VERSION=3.11"
         image: f213/django
         name: make sure docker image is buildable
         path: testproject
         requires:
           - build
