name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build
        uses: ./.github/actions/build

      - name: restore mypy cache
        uses: actions/cache@v3
        with:
          path: .mypy_cache
          key: mypy-cache-${{ github.ref_name }}
          restore-keys: mypy-cache-master

      - name: checks
        run: make checks

  test:
    needs: checks
    runs-on: ${{ contains(github.triggering_actor, "[bot]") && "ubuntu-latest" || "ubuntu-8x" }}
    services:
      postgres:
        image: postgres:13.9-alpine
        env:
          POSTGRES_PASSWORD: secret
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis:6.2.10-alpine
        ports:
          - 6379:6379

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build
        uses: ./.github/actions/build

      - name: install locale stuff
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: locales-all gettext
          version: 1

      - name: get number of cpu cores
        uses: SimenB/github-actions-cpu-cores@v2.0.0
        id: cpu-cores

      - name: test
        env:
          DATABASE_URL: postgres://postgres:secret@localhost:5432/postgres
        run: make test -e numprocesses=${{ steps.cpu-cores.outputs.count }}
