name: child project workflow run

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: run
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run ./{{ cookiecutter.name }}/.github/workflows/ci.yml
