name: child project workflow run

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run:
    defaults:
      run:
        working-directory: '{{ cookiecutter.name }}'
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: run
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run ./.github/workflows/ci.yml
